# Generated by Django 4.1.1 on 2022-10-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag',
            new_name='tags',
        ),
    ]
