# Generated by Django 4.1.1 on 2022-10-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_rename_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featuree_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
