# Generated by Django 4.1.1 on 2022-10-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_project_featuree_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featuree_image',
            new_name='featured_image',
        ),
    ]
